version: '2'
services:
  mongo:
    image: tutum/mongodb:3.2
    environment:
     - MONGODB_PASS=""
     - MONGODB_DATABASE="admin"
     - AUTH=no
  backend:
    build: .
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    depends_on:
      - backend
    labels:
        traefik.enable: "true"
        traefik.frontend.rule: "Host:assetmanagement.impressione.me"
        traefik.port: "80"
        traefik.frontend.redirect.entryPoint: "https"
